### ISSUE TITLE
怎么安装第一个.js啊？纯小白

### ISSUE THREAD

**Issue by lilbeauty** [1c7/Youtube-Auto-subtitle-to-chinese-subtitle-download#2]

**Comment by 1c7** [comment]
1. 使用  Chrome 浏览器（Firefox 和  Edge 未经测试）
 2. 安装 tampermonkey https://chrome.google.com/webstore/detail/tampermonkey/dhdgffkkebhmkfjojejmpbldmpobfkfo
 3. 安装这个脚本: https://greasyfork.org/zh-CN/scripts/38941-youtube-%E7%BF%BB%E8%AF%91%E4%B8%AD%E6%96%87%E5%AD%97%E5%B9%95%E4%B8%8B%E8%BD%BD-v13
